version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- nuget restore ./PCTime/PCTimeTest/packages.config -PackagesDirectory ./PCTime/packages
build:
  project: ./PCTime/PCTime.sln
  verbosity: minimal

test_script:
    nunit-console ./PCTime/PCTimeTest/PCTimeTest.csproj /xml:nunit-results.xml /config:Release

